### ISSUE TITLE
Kompatibilität mit 4.7 und contao/tcpdf-bundle

### ISSUE THREAD

**Issue by jankout** [do-while/contao-pdfforms-bundle#1]
Hallo, 

leider funktioniert die Erweiterung mit Contao 4.7 und der Erweiterung contao/tcpdf-bundle nicht mehr. Ich habe Ihnen bereits eine Mail geschickt. Hier noch einmal die Fehlermeldung. 

`[2019-05-24 19:53:34] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: require_once(): Failed opening required '/homepages/35/d432404500/htdocs/contao4/vendor/contao/core-bundle/src/Resources/contao/config/tcpdf.php' (include_path='.:/usr/lib/php7.1')" at /homepages/35/d432404500/htdocs/contao4/vendor/do-while/contao-pdfforms-bundle/src/Resources/contao/classes/PdfformsHelper.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code line 14 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: require_once(): Failed opening required '/homepages/35/d432404500/htdocs/contao4/vendor/contao/core-bundle/src/Resources/contao/config/tcpdf.php' (include_path='.:/usr/lib/php7.1') at /homepages/35/d432404500/htdocs/contao4/vendor/do-while/contao-pdfforms-bundle/src/Resources/contao/classes/PdfformsHelper.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code:14)"} []`

**Comment by do-while** [comment]
Ich bin gerade dran, das betrifft alle meine PDF-Erweiterungen.
Grund ist, dass ab Contao 4.7 TCPDF nicht mehr im Core ist.

Lösung kommt wahrscheinlich noch heute.

**Comment by do-while** [comment]
Kurzfristig wird es helfen, wenn man die **vendor/contao/tcpdf-bundle/src/Resources/contao/config/tcpdf.php** nach **vendor/contao/core-bundle/src/Resources/contao/config/tcpdf.php** kopiert.

Aber bald ist der funktionierende Update da.

**Comment by jankout** [comment]
Ok, danke für die schnelle Antwort. Ich habe es meinem Kunden mitgeteilt. Wenn es heute Abend fertig wird, kann ich noch warten.

**Comment by do-while** [comment]
Die Version 1.5.0 sollte jetzt keine Probleme mehr mit Contao 4.7 machen.

**Comment by jankout** [comment]
Super. Vielen Dank.
