### ISSUE TITLE
Passwortgeschützte Dateien drucken mit iOS

### ISSUE THREAD

**Issue by takhadnotor** [do-while/contao-pdfforms-bundle#11]
Aus Erfahrungsberichten meiner Seitenbesucher weiß ich, dass sobald der Haken bei "PDF schützen" gesetzt ist, mit iOS-Geräten nicht mehr gedruckt werden kann, weil ein Passwort fürs Drucken gefordert wird. Das Ganze passiert auch, wenn das Feld "PDF-Passwort für Berechtigungen" nicht ausgefüllt ist. Das macht das Sperren von PDFs mit einem Passwort für den produktiven Einsatz leider unbrauchbar. Diesen Bug gibt es nur bei iOS. MacOS, Linux und Windows machen keine Probleme. Vermutlich liegt es am Betriebssystem, aber gibt es dafür eine Lösung?

**Comment by do-while** [comment]
Wenn das "PDF-Passwort für Berechtigungen" nicht ausgefüllt wird, wird das PDF mit einem Zufallspasswort geschützt. Es gibt ja keinen Sinn, etwas zu schützen und die Schutzeinstellungen zugänglich zu lassen.
Für das Drucken muß dann "Drucken" und "Drucken in hoher Auflösung" angehakt sein, dann sollte das PDF auch ohne Passwort druckbar sein.
Das Feld "Passwort zum Öffnen" muss natürlich leer bleiben.

Ich kann das Problem nicht nachvollziehen, da ich keine aktuellen iOS-Geräte habe.

Die Schutzmechanismen sind im Modul TCPDF enthalten, was von der Erweiterung genutzt wird. Sollte also das Druckproblem weiterhin bestehen, müssen wir uns dort hin wenden.
