### ISSUE TITLE
Dev Mode - Contao-Manager läuft nicht durch, Error bei cache clear

### ISSUE THREAD

**Issue by timmuz** [do-while/contao-pdfforms-bundle#12]
Hallo do-while, ich bin auf ein Problem gestoßen, bei dem ich den Contao-Manager und Weiteres nicht wie erwartet verwenden kann. Es scheint mit diesem Bundle zusammenzuhängen. Ich erkläre kurz die Steps:

1. Dev modus in .env.local Datei einschalten mit "APP_ENV=dev"
2. Contao-Manager im Browser öffnen
3. Es wird ein Fehler angezeigt, dass die Datenbankverbindung nicht korrekt eingestellt wäre und sie lässt sich dann auch nicht anpassen im Manager.

- Sobald ich den dev Modus ausschalte, gibt es dieses Problem nicht mehr.
- ein cache:clear über die contao-console funktioniert ebenfalls nicht, hierbei erhalte ich weitere Auskunft zur Ursache des/eines Problems:

      In tl_pdff_positions.php line 21:                                                
      Warning: Undefined array key "deleteConfirm"

Getestet unter:
contao-pdfforms-bundle -> "versions : * 1.6.4" 
contao -> 4.13.35
in verschiedenen docker umgebungen

**Comment by do-while** [comment]
Die Fehlermeldung ist beseitigt in 1.6.5
