### ISSUE TITLE
Rechte "PDF-Formular ausfüllen" ist nicht möglich

### ISSUE THREAD

**Issue by lizzylotty** [do-while/contao-pdfforms-bundle#13]
Hallo,

ich nutze aktuell eine Demoversion, die Lizenz ist beantragt.

Ich habe das Problem, dass ich dem Redakteur nicht alle benötigten Rechte zuweisen kann. "Position und Attribute" geht, allerdings bräuchte ich auch "PDF-Formular ausfüllen" - diese Haken kann ich nicht setzen. 
Wenn ich in der Benutzergruppe in der Struktur bei "tl_pdff_positions" die Checkboxen aktiviere, springen mir die Haken nach dem Speichern einfach wieder raus.

Ich freue mich über Hilfe! Danke und liebe Grüße :)

**Comment by do-while** [comment]
Das kann ich nicht nachvollziehen, hier hat auch die Erweiterung keinen Einfluß auf das Speichern der Datenbankfreigaben.
Ich könnte mir vorstellen, dass in dem Hosting die Größe der Formular-Postdaten zu gering eingestellt sind, so dass bei vielen Erweiterungen und Checkboxen nicht alle Daten an Contao übertragen werden.
Es könnte an der PHP Variablen **max_input_vars** liegen.

Die Demo hat überall die gleichen Einstellungen, wie auch die lizensierte Version, daran kann es auch nicht liegen.

**Comment by lizzylotty** [comment]
Das war es. Vielen Dank!!!

**Comment by do-while** [comment]
Dank für's Feedback
