### ISSUE TITLE
Home-Verzeichnis als Speicherort verwenden

### ISSUE THREAD

**Issue by swinde** [do-while/contao-pdfforms-bundle#2]
Hallo,
wäre es machbar als Speicherort für die Pdf Datei das Home-Verzeichnis als Dateiquelle zu verwenden, wenn sich ein Mitglied angemeldet hat?

**Comment by do-while** [comment]
Zurzeit ist das leider nicht möglich, aber ich werde das Ticket mal offen lassen, damit ich das in de3r nächsten Version ggf. berücksichtigen kann.
Das würde dann nur bei angemeldeten Mitgliedern funktionieren, man müßte also entweder alle nicht angemeldeten ohne PDF lassen oder ein Fallback-Verzeichnis angeben, wo die PDF gespeichert wird, wenn kein Mitglied angemeldet ist oder wenn beim Mitglied kein Benutzerverzeichnis definiert ist.

**Comment by swinde** [comment]
Danke fürs vormerken.
In meinem Fall bräuchte ich das nur für angemeldete Mitglieder. 
Im "Mischfall" könnte man das ja auch über zwei separate Formulare lösen.

**Comment by swinde** [comment]
Hallo ich wollte das Issue noch einmal pushen. 
Ich habe gesehen, das die Version für des Notification Center das auch kann.

**Comment by zonky2** [comment]
ich habe das "hartverdrahtet" mal eingebaut - man kann die andere Auswahl eines Ordners als "Fallback" belassen...
btw: die Auswahl des Ordners sollte Pflichtfeld sein - ansonsten macht das wenig Sinn bzw. es wird eine Fehlermeldung geworfen.

**Comment by zonky2** [comment]
?

**Comment by swinde** [comment]
Hi. Ich kann das.? nicht zuordnen.

**Comment by zonky2** [comment]
ging an @do-while like "wie gehts weiter"...

**Comment by do-while** [comment]
Ich gucke mal jetzt am Wochenende, was ich machen kann.

**Comment by zonky2** [comment]
Prio 1 sollte https://github.com/do-while/contao-pdfforms-bundle/issues/9#issuecomment-1351541702 haben...

**Comment by do-while** [comment]
Heute habe ich es endlich geschafft, die neue Version für Contao ^5.3
Ein Speichern im Homeverzeichnis ist auch enthalten.
