### ISSUE TITLE
PDF download

### ISSUE THREAD

**Issue by lizzy-lotty** [do-while/contao-pdfforms-bundle#3]
Hallo,
ist es denn auch möglich die PDF direkt nach absenden des Formulars über den Browser herunterzuladen oder die PDF auf der Weiterleitungsseite als Download zur Verfügung gestellt wird?
Vielen lieben Dank!!

**Comment by do-while** [comment]
Ja, klar das geht mit InsertTags ([siehe Handbuch](https://www.softleister.de/contao-pdfforms-bundle.html?file=files/manuals/contao-pdfforms-bundle/Anleitung_contao-pdfforms-bundle.pdf) Seite 7 - InsertTags):
Die Erweiterung stellt auch eigene InsertTags zur Verfügung:

`{{pdf_forms::pdfdocument}}`
kann verwendet werden, um den Dateilink des erzeugten Dokuments in einen
Download-Link einzubauen.

`{{pdf_forms::pdfdocument::name}}`
kann verwendet werden, um nur den Dateinamen des erzeugten Dokuments in der
Antwortseite einzufügen.
