### ISSUE TITLE
Alte Daten 

### ISSUE THREAD

**Issue by Benjamin-Scherf** [do-while/contao-pdfforms-bundle#4]
Hallo,

ich benutze die Extension in Zusammenspiel mit einem Catalog. Hier werden Datensätze gespeichert und in der Detailansicht per Javascript an ein normales Formular übergeben. 
Das Formular ist sieben seitig und beinhaltet einige hundert Felder.

Nun ergibt sich ein eigenartiges Verhalten. Ab und zu kommt es vor, dass beim Speichern des einen Datensatzes noch Daten aus einem anderen Datensatz in das PDF übertragen werden. Das passiert in verschiedene Richtungen, zumeist jedeoch betrifft es den Datensatz, welcher weniger Daten aufweist. Hier finden sich dann Daten aus einem vorher übertragenen Formular. 

Die Befüllung des Formulars klappt immer einwandfrei, eine Verwechslung der erzeugeten PDF Dateien kann ich auch ausschließen. 

Ist das Problem bekannt? Benutzt die Extension vielleicht so etwas wie einen cache?

Vielen Dank

**Comment by Benjamin-Scherf** [comment]
Ergänzugn:
Insbesondere Betrift das eine Liste.

Liste Dokument A:
1 = A1
2 = A2
3 = A3
4 = A4

Liste Dokumen B mit weniger Datensätze:
1 = B1
2 = B2
3 = A3 (Obwohl per Javascript gelöscht und nicht befüllt)
4 = A4 (Obwohl per Javascript gelöscht und nicht befüllt)

**Comment by do-while** [comment]
Ein Cache gibt es da nicht. Kann es sein, dass durch die mehrseitigen Formulare, die sicherlich ihre Daten in der Session übertragen, da doch die Daten aus Dokument A noch übergeben werden?

Ich werde das mal versuchen nachzustellen. Wenn es am pdfforms liegt, müßte das ja auch passieren, wenn man vor Absenden des Dokument B die Felder deaktiviert im Formular.

Gibt es vielleicht ein Schlüsselfeld, woran man den Umfang erkennen kann, oder ein verstecktes Feld, so dass man in den Formulareigenschaften mit der "Mehrformular-Vorlage" arbeiten kann?

**Comment by Benjamin-Scherf** [comment]
> Wenn es am pdfforms liegt, müßte das ja auch passieren, wenn man vor Absenden des Dokument B die Felder deaktiviert im Formular.

Das kann ich auch mal testeb. Interessanter Weise lhabe ich per Javascript alle Felder nach unten, die ich in einem Formular nicht benötige gelöscht. Und trotzdem wurden die die Daten aus dem vorhergehenden Formular mit übermittelt. Ich habe es jetzt so gelöst, dass ich alle Felder behalte aber den Inhalt leere. Damit funktioniert es. 

Die Mehrformulareingabe werde ich testen.
