### ISSUE TITLE
Namensfeld bei Positions-Item

### ISSUE THREAD

**Issue by zonky2** [do-while/contao-pdfforms-bundle#5]
ein zus. Namensfeld beim Positions-Item wäre gut, damit man in der Liste eine Idee hat, wofür das Feld ist - siehe Screenshot

![screenshot_801](https://user-images.githubusercontent.com/1045318/72594274-5dd4c180-3907-11ea-962a-5bea3e80b39a.png)

die Ausgabe in Liste würde ich als "Präfix" machen, d.h. wenn vorhanden, dann vor das "x" z.B. ein "Meinfeld AGB" zu "Meinfeld AGB: x"

**Comment by zonky2** [comment]
?

**Comment by do-while** [comment]
Heute habe ich es endlich geschafft, die neue Version für Contao ^5.3
Das Feld für Bemerkungen und Notizen ist jetzt auch dabei
