### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by Schmidty2** [do-while/contao-pdfforms-bundle#6]
Hallo,
beim leeren des Caches über den Contao-Manager wird folgende Fehlermeldung ausgegeben:

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /www/htdocs/w0123456/verzeichnis/vendor/do-while/contao-pdfforms-bundle/src/Resources/contao/classes/PdfformsHelper.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code on line 324

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /www/htdocs/w0123456/verzeichnis/vendor/do-while/contao-pdfforms-bundle/src/Resources/contao/classes/PdfformsHelper.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code on line 343
 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.   

PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /www/htdocs/w0123456/verzeichnis/vendor/do-while/contao-pdfforms-bundle/src/Resources/contao/classes/PdfformsHelper.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code on line 324

PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /www/htdocs/w0123456/verzeichnis/vendor/do-while/contao-pdfforms-bundle/src/Resources/contao/classes/PdfformsHelper.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code on line 343`

Provider: All-Inkl Business
Contao: 4.9.1
Manager: 1.2.4
PHP: 7.3
Contao Pdfforms Bundle:  1.5.1

**Comment by do-while** [comment]
In PHP 7.3 wird in switch-Blöcken ein "continue" und ein "break" nahezu gleich gestellt. Das führt dazu, dass es Probleme gibt, wenn man beispielsweise ein switch innerhalb einer while-Schleife verwendet und dort mit einem continue die while-Schleife abkürzen möchte. Für diesen Fall muss jetzt dann "continue 2" verwendet werden, daher das Warning.

Ich habe diese Strukturen jetzt in der neuen Version 1.5.2 überarbeitet und korrigiert.

**Comment by Schmidty2** [comment]
Funktioniert, Danke
