### ISSUE TITLE
Inkompatibel mit mp_forms (Terminal42)?

### ISSUE THREAD

**Issue by wuapaadev** [do-while/contao-pdfforms-bundle#7]
Hallo do-while,

kann es sein das die Erweiterung mit mp_forms von terminal42 nicht zusammenspielt? In einem mehrseitigen Formular wird bei jedem Formular-Seitenwechsel ein PDF erzeugt, Inhalt jeweils nur die Formularfelder der aktuell angezeigten Seite.

Lässt sich das beheben, oder gibt es Alternativen?

Version Contao: 4.9.9
do-while/contao-pdfforms-bundle : 1.5.3
terminal42/contao-mp_forms: 4.1.0

**Comment by do-while** [comment]
Guten Tag wuapaadev,

das ist richtig, da der PDF-Generator direkt am Submit hängt wird er bei jedem 
Teilformular auch getriggert. Das läßt sich leider auch nicht verhindern, da ich mich 
in einem sehr frühen Hook einklinken muss, um dann das PDF als Upload-Datei in 
die Submit-Daten reinzuschummeln.
Das Problem ist bekannt und es gibt für diese Erweiterung keine Lösung.

Alternativ gibt es die Erweiterung do-while/contao-pdf-nc-attachment-bundle
Die Funktionalität ist sehr ähnlich, der PDF-Generator hängt nur nicht am Formular, 
sondern am Gateway des Notification-Centers. Da als Eingangsdaten dort die 
SimpleTokens verwendet werden, hat man viel mehr Möglichkeiten als in pdfforms.
Bei Registrierungen oder beliebigen anderen Benachrichtigungsquellen kann ein 
PDF generiert werden. Die Erweiterung hat mehr Möglichkeiten, sie kann auch Bilder 
aus der Dateiverwaltung, dem Upload oder einem Bytestrean einbinden (z.B. aus 
dem Unterschriftenfeld).
Die Angabe der Positionen ist identisch, nur eben mit SimpleTokens.
Auch hierfür gibt es eine Demo im Contao-Manager, die auf 2 Seiten begrenzt ist.

Wenn Ihr auf diese Erweiterung umschwenken möchtet, schicke mir bitte eine kurze 
Nachricht, dann buche ich Euch kostenfrei um und Ihr bekommt einen neuen Lizenzcode.
