### ISSUE TITLE
Fehler in der Darstellung von slowenischen Sonderzeichen

### ISSUE THREAD

**Issue by wuapaadev** [do-while/contao-pdfforms-bundle#8]
Hallo do-while,

in einem PDF wird das slowenische Zeichen "Č" bzw. "č" als "?" dargestellt. (s.u.).  Ich vermute hier die Ursache bei TCPDF - möglicherweise ist der Zeichensatz nicht vollständig der standardmäßig mit pdfforms verwendet wird...

Definition im Backend (Testweise 5. Eintrag "a_vorname....."): 
![Screenshot 2021-06-08 at 13-51-43 Formulare bcdev wuapaa at](https://user-images.githubusercontent.com/63860594/121187393-4e417a00-c868-11eb-9d18-9018c4234a6f.png)

Ergebnis im Testpdf
![Screenshot 2021-06-08 at 13-51-16 Anmeldung_Unternehmer__DE pdf](https://user-images.githubusercontent.com/63860594/121187409-51d50100-c868-11eb-8d76-c8fc776262e5.png)

Installierte Version: 1.6.1

**Comment by do-while** [comment]
Hallo wuapaadev,

ja, das wird dann am verwendeten Font liegen.

In contao-pdfform-bundle ab Version 1.6 ist auf einfache Weise die Verwendung eigener 
Fonts möglich (in den Formulareigenschaften einzustellen). Da sollte dann ein geeigneter 
Font verwendet werden können.
