### ISSUE TITLE
Error with crypted PdfformsHelper.php on PHP8

### ISSUE THREAD

**Issue by ACCakut** [do-while/contao-pdfforms-bundle#9]
{"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0) Compile Error: Array and string offset access syntax with curly braces is no longer supported at
....../httpdocs/vendor/do-while/contao-pdfforms-bundle/src/Resources/contao/classes/PdfformsHelper.php:1)"} []

I think this is due to PHP8 were this deprecated notation is blocked.

**Comment by do-while** [comment]
Meine Erweiterungen sind alle noch nicht mit PHP 8 getestet.
Bis PHP 7.4 sollte alle funktionieren

**Comment by peerlight** [comment]
Hallo, 

gibts Neuigkeiten zu dem Thema?

In einer Contao 4.13 auf PHP 8.1 lief es einige Zeit problemlos. Spontan bekomme ich heute diese Fehlermeldung und das ganze Frontend ist weg:
`Uncaught PHP Exception ErrorException: "Warning: Undefined variable $O0O000O00" at /www/htdocs/DOMAIN/vendor/do-while/contao-pdfforms-bundle/src/Resources/contao/classes/PdfformsHelper.php line 1`

**Comment by do-while** [comment]
Die aktuelle Version funktioniert mit PHP 8.1, die Meldung ist lediglich eine Warnung, die aber die Funktion nicht weiter beeinträchtigen sollte. Nur im Debug-Modus bei Contao wird es leider nicht funktionieren. Ich bin da dran.

**Comment by peerlight** [comment]
Danke. Ja, es wahr wohl der DebugMode den ich wegen anderer Dinge angeworfen hatte.

**Comment by zonky2** [comment]
> die Meldung ist lediglich eine Warnung, die aber die Funktion nicht weiter beeinträchtigen sollte. Nur im Debug-Modus bei Contao wird es leider nicht funktionieren. Ich bin da dran.

Moin, leider hat sich an der Stelle offensichtlich nichts getan - die Meldung kommt immer noch und **blockiert damit alle anderen Debugausgaben!** Man kann die Warnings zwar per config.yml unterbinden, aber das ist ja nicht Sinn der Sache.

Mit Deinem Obfuscator bzw. privaten Dateien kann man da auch keinen PR machen - ggf. hilft eine neuere Version von Deinem Obfuscator-Tool...

**Comment by do-while** [comment]
Die Warnung ist endlich weg. Neues Release: 1.6.4
